#!/bin/bash

if [ "$SHELL" == /bin/zsh ]
then
  SHELL_TYPE="zsh"
  PROFILE_FILE=~/.zprofile
else
  SHELL_TYPE="bash"
  PROFILE_FILE=~/.bash_profile
fi

echo "Setting up image-sort for shell type: $SHELL_TYPE"

if grep -q "image-sort/sizzle.py" $PROFILE_FILE
then
  echo "Alias for image-sort already found in $PROFILE_FILE deleting it"
  sed -i '' '/image-sort/d' $PROFILE_FILE
fi

echo "alias image-sort='python $HOME/image-sort/sizzle.py'" >> $PROFILE_FILE
